In [1]:
import os

from dotenv import load_dotenv

import daft
from daft import col, lit
from daft.functions import download, format
from daft.io import IOConfig, S3Config
from daft.unity_catalog import UnityCatalog

load_dotenv()

True

In [2]:
daft.set_planning_config(
    default_io_config=IOConfig(
        s3=S3Config(
            region_name="us-west-2",
            key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            # session_token=os.getenv("AWS_SESSION_TOKEN")
        )
    )
)

DaftContext(_ctx=<builtins.PyDaftContext object at 0x10fbb2010>)

In [3]:
SOURCE_URI = "s3://daft-public-datasets/reddit-irl/source"
COMMENTS_URI = "s3://daft-public-datasets/reddit-irl/comments.parquet"
qe_uri = "s3://daft-public-datasets/reddit-irl/embeddings/Qwen--Qwen3-Embedding-0.6B.parquet/*.parquet"
reviews_uri = "s3://srinu-dump/amazon-reviews/"
DEST_URI = "s3://daft-public-datasets/reddit-irl/all_images"
INDEX_URI = f"{DEST_URI}/_reddit_irl_images_index.parquet"

In [5]:
unity = UnityCatalog(
    endpoint=os.getenv("DATABRICKS_ENDPOINT"),
    token=os.getenv("DATABRICKS_TOKEN"),
)

catalog = daft.Catalog.from_unity(unity)

table = catalog.get_table("jaytest-unity.demo.reddit_irl_images_index")
print(table)

Table('reddit_irl_images_index')

In [7]:
IMAGES_URI = "s3://srinu-dump/conceptual-captions-12m-webdataset-images-v3/"
IMAGES_INDEX_URI = f"{IMAGES_URI}/_all_images_index.parquet"
files_df = daft.from_glob_path(f"{IMAGES_URI}/*.png").write_parquet(f"{IMAGES_URI}/_all_images_index.parquet")

Error when running pipeline node GlobScanSource
RuntimeStatsManager finished with active nodes {0}

FileNotFoundError: File: s3://srinu-dump/conceptual-captions-12m-webdataset-images-v3//*.png not found
No files found

In [4]:
df = daft.read_parquet(COMMENTS_URI)

df.show()

🗡️ 🐟 Parquet Scan: 00:00

In [ ]:
df = daft.read_parquet("s3://srinu-dump/amazon-reviews-embeddings/_stats2.parquet").sort("rows_per_second", desc=True)

df.show()

In [17]:
files_df = daft.from_glob_path(f"{DEST_URI}/*.png")

# Extract metadata from path and include file info from glob
index_df = (
    files_df.with_column("id", col("path").regexp_extract(r"_id([a-zA-Z0-9]+)\.png$", 1)).with_column(
        "image_xxhash",
        col("path").regexp_extract(r"_xxhash([0-9]+)_id", 1).cast(daft.DataType.uint64()),
    )
).show()

In [ ]:
SOURCE_URI = "s3://daft-public-datasets/reddit-irl"


df = daft.read_parquet(f"{SOURCE_URI}/*.parquet")

df = (
    df.with_column("created_utc", col("created_utc").cast(daft.DataType.timestamp("ms", "UTC")))
    .where(col("url").length() > 0)
    .with_column("bytes", download(daft.col("url"), on_error="null"))
    .where(col("bytes").not_null())
    .with_column("image_path", format("{}/{}.png", lit(SOURCE_URI), lit("image")))
    .with_column("image_written", image_writer.write_images(col("bytes"), col("image_path")))
)
df.limit(10).show()

In [ ]:
columns = [
    "type",
    "id",
    "subreddit.id",
    "subreddit.name",
    "subreddit.nsfw",
    "title",
    "created_utc",
    "permalink",
    "domain",
    "score",
    col("url").alias("image_url"),
    col("image_written").alias("image_s3_uri"),
]
df.select(columns).write_parquet(f"{DEST_URI}/_reddit_irl_index.parquet")

In [27]:
df = daft.read_parquet(COMMENTS_URI)
df.show()

DaftCoreException: DaftError::External Unhandled Error for path: s3://daft-public-datasets/reddit-irl/comments.parquet
Details:
unhandled error: Error { s3_extended_request_id: "WSE2Rc3ifr2EQBOzPF1mRhlhALux5GCCSxviSmayK6jK3zCAdAG5zwSVQAX6IlNZbAHuB26L3Fw=", aws_request_id: "ER9SW7Z963HEF86D" } (Unhandled(Unhandled { source: ErrorMetadata { code: None, message: None, extras: Some({"s3_extended_request_id": "WSE2Rc3ifr2EQBOzPF1mRhlhALux5GCCSxviSmayK6jK3zCAdAG5zwSVQAX6IlNZbAHuB26L3Fw=", "aws_request_id": "ER9SW7Z963HEF86D"}) }, meta: ErrorMetadata { code: None, message: None, extras: None } }))